### PR TITLE
Randomise project list on each render

### PR DESCRIPTION
**Pull request by pareshchouhan**
Randomise project list on each render for better visibility.

### CODE REVIEW

**Comment by pareshchouhan** [comment]
Can move it to componentWillReceiveProps or post sort as well, your call.

**Comment by ArionMiles** [comment]
I'm actually trying to get the `Newest Addition` sorting to work on loading. As you may have noticed, when you first load the /projects endpoint, the cards are not in descending order (newest first), even though the default `sortValue` is set to that here: https://github.com/ArionMiles/hikaru/blob/master/src/components/projects/ProjectsPage.js#L23

If we can have this, that'd be nice. BTW, why have you written a knuth shuffle function when we already import it in the same file?

**Comment by pareshchouhan** [comment]
Oh, I missed that knuth-shuffle, will remove mine. ok let me see why this sort isn't working.

**Comment by pareshchouhan** [comment]
Closing this.

**Pull request closed without merging**
